# Generated by Django 4.2.7 on 2025-10-05 13:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_participants', models.PositiveIntegerField(verbose_name='Total de Participantes')),
                ('total_hours', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Total de Horas Voluntariadas')),
                ('trash_collected_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Lixo Coletado (kg)')),
                ('trees_planted', models.PositiveIntegerField(blank=True, null=True, verbose_name='Árvores Plantadas')),
                ('area_cleaned_m2', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Área Limpa (m²)')),
                ('recyclable_material_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Material Reciclável (kg)')),
                ('summary', models.TextField(verbose_name='Resumo do Evento')),
                ('challenges', models.TextField(blank=True, verbose_name='Desafios Encontrados')),
                ('achievements', models.TextField(blank=True, verbose_name='Conquistas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='events.event', verbose_name='Evento')),
            ],
            options={
                'verbose_name': 'Relatório do Evento',
                'verbose_name_plural': 'Relatórios dos Eventos',
                'ordering': ['-created_at'],
            },
        ),
    ]
